import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {gunzipSync} from 'node:zlib';import {createFolioServer} from '../server/index.mjs';
test('AI routes require local authorization, persist grounded answers and exclude credentials from backup',async t=>{
 const dataDir=await mkdtemp(path.join(tmpdir(),'folio-chat-http-'));let calls=0;
 const server=await createFolioServer({dataDir,codexFactory:()=>({status:async()=>({installed:false,connected:false}),shutdown:async()=>{}}),secretStorage:{encrypt:s=>'wrapped-'+Buffer.from(s).toString('base64'),decrypt:s=>Buffer.from(s.slice(8),'base64').toString()},aiGenerate:async()=>{calls++;return 'A test answer [p. 1].';}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));await rm(dataDir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`;const {token}=await(await fetch(base+'/api/session')).json();const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};const call=(url,method='GET',body)=>fetch(base+url,{method,headers,...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await fetch(base+'/api/ai/settings')).status,401);assert.equal((await fetch(base+'/api/ai/settings',{headers:{...headers,Origin:'chrome-extension://'+'a'.repeat(32)}})).status,403);
 const pdf=await(await fetch(base+'/api/pdfs',{method:'POST',headers:{...headers,'Content-Type':'application/pdf'},body:'%PDF-test'})).json();await call('/api/capture','POST',{title:'Paper',pdfId:pdf.pdfId});await call('/api/reading-cache/'+pdf.pdfId,'PUT',{version:1,pages:[{number:1,paragraphs:['A scientific finding.']}],figures:[],warnings:[]});const route='/api/ai/papers/'+pdf.pdfId;
 assert.equal((await call('/api/ai/settings','POST',{provider:'openai',model:'test',key:'private-key-fixture'})).status,200);assert.equal((await readFile(path.join(dataDir,'paper-chat/settings.json'),'utf8')).includes('private-key-fixture'),false);
 assert.equal((await call(route,'POST',{question:'Summarize',summary:true})).status,403);assert.equal(calls,0);await call(route,'PUT',{enabled:true,provider:'openai'});assert.equal((await call(route,'POST',{question:'',summary:true})).status,200);assert.equal(calls,1);
 const state=await(await call(route)).json();assert.equal(state.messages.length,2);assert.deepEqual(state.messages[1].pages,[1]);const backup=gunzipSync(Buffer.from(await(await call('/api/backup')).arrayBuffer()));assert.ok(backup.includes(Buffer.from('A test answer')));assert.ok(!backup.includes(Buffer.from('wrapped-')));assert.ok(!backup.includes(Buffer.from('private-key-fixture')));
 await call('/api/reading-cache/'+pdf.pdfId,'DELETE');assert.equal((await(await call(route)).json()).messages.length,2);await call(route,'DELETE');assert.equal((await(await call(route)).json()).messages.length,0);
});
