import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile, mkdtemp, rm, writeFile} from 'node:fs/promises';
import {statSync} from 'node:fs';
import {createRequire} from 'node:module';
import {runInNewContext} from 'node:vm';
import {homedir, tmpdir} from 'node:os';
import path from 'node:path';
import JSZip from 'jszip';
import {DOMParser, XMLSerializer} from '@xmldom/xmldom';
import {extractDocx, generateDocx} from '../server/word.mjs';
import {defaultDataDir} from '../server/index.mjs';

// Frozen fictional fixture generated by Folio 0.1.3, public commit
// 7959442a4c8e4c7ca41b09cb1ffe8ec6540515bb. Never regenerate it with current
// code: it checks real pre-rename compatibility, independently of this writer.
const fixture = new URL('./fixtures/folio-0.1.3-revision.docx', import.meta.url);
const W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const nodes = (doc, name) => Array.from(doc.getElementsByTagNameNS(W, name));
const tag = node => nodes(node, 'tag')[0]?.getAttributeNS(W, 'val');
const authorNote = 'Author note: verify the fictional example before sharing.';

test('Refhaven revises a frozen Folio Word export without losing legacy identity or author notes', async () => {
  const buffer = await readFile(fixture);
  const original = await extractDocx(buffer);
  assert.equal(original.revision, true);
  assert.match(original.text, /\(folio:legacy-fictional-paper\)/);
  assert.ok(original.text.includes(authorNote));
  assert.equal(original.embeddedPapers.length, 1);
  assert.equal(original.embeddedPapers[0].id, 'legacy-fictional-paper');
  assert.equal(original.embeddedPapers[0].notes, undefined);
  assert.equal(original.embeddedPapers[0].pdfPath, undefined);

  const zip = await JSZip.loadAsync(buffer);
  for (const entry of Object.values(zip.files).filter(entry => !entry.dir)) {
    assert.doesNotMatch(await entry.async('string'), /SYNTHETIC_PRIVATE_NOTE_MUST_NOT_EXPORT|private-not-exported\.pdf|\/Users\//);
  }
  const doc = new DOMParser().parseFromString(await zip.file('word/document.xml').async('string'), 'application/xml');
  const paragraph = doc.createElementNS(W, 'w:p');
  const run = doc.createElementNS(W, 'w:r');
  const text = doc.createElementNS(W, 'w:t');
  text.textContent = 'Revision adds another fictional source (folio:revision-fictional-paper).';
  run.appendChild(text);
  paragraph.appendChild(run);
  const body = nodes(doc, 'body')[0];
  body.insertBefore(paragraph, body.firstChild);
  zip.file('word/document.xml', new XMLSerializer().serializeToString(doc));
  const added = {id:'revision-fictional-paper', title:'Another fictional organization study', authors:'Example, Blair', year:'2026', journal:'Fictional Methods Journal'};
  let revised = (await generateDocx(await zip.generateAsync({type:'nodebuffer'}), [added], 'apa')).buffer;
  for (const style of ['nature', 'vancouver']) {
    // No library records: both old and newly added sources must survive in Word.
    const output = await generateDocx(revised, [], style);
    assert.deepEqual(output.unresolved, []);
    assert.equal(output.citations.length, 2);
    assert.equal(output.bibliography.length, 2);
    revised = output.buffer;
    const recovered = await extractDocx(revised);
    assert.deepEqual(recovered.embeddedPapers.map(paper => paper.id).sort(), ['legacy-fictional-paper', 'revision-fictional-paper']);
    assert.match(recovered.text, /\(folio:legacy-fictional-paper\)/);
    assert.match(recovered.text, /\(folio:revision-fictional-paper\)/);
    assert.ok(recovered.text.includes(authorNote));
    assert.doesNotMatch(recovered.text, /References/);
    const updatedZip = await JSZip.loadAsync(revised);
    const updatedDoc = new DOMParser().parseFromString(await updatedZip.file('word/document.xml').async('string'), 'application/xml');
    assert.equal(nodes(updatedDoc, 'sdt').filter(node => tag(node) === 'folio:bibliography').length, 1);
  }
});

test('renamed app retains the legacy library location and explicit FOLIO_DATA_DIR override', () => {
  const previous = process.env.FOLIO_DATA_DIR;
  try {
    delete process.env.FOLIO_DATA_DIR;
    const legacy = process.platform === 'darwin' ? path.join(homedir(), 'Library/Application Support/Folio')
      : process.platform === 'win32' ? path.join(process.env.LOCALAPPDATA || homedir(), 'Folio')
      : path.join(process.env.XDG_DATA_HOME || path.join(homedir(), '.local/share'), 'folio');
    assert.equal(defaultDataDir(), legacy);
    const explicit = path.join(tmpdir(), 'refhaven-legacy-override-fixture');
    process.env.FOLIO_DATA_DIR = explicit;
    assert.equal(defaultDataDir(), explicit);
    process.env.FOLIO_DATA_DIR = '';
    assert.equal(defaultDataDir(), legacy);
  } finally {
    if (previous === undefined) delete process.env.FOLIO_DATA_DIR;
    else process.env.FOLIO_DATA_DIR = previous;
  }
});

test('desktop startup creates the legacy profile before locking and preserves an existing profile', async t => {
  const appData = await mkdtemp(path.join(tmpdir(), 'refhaven-startup-'));
  t.after(() => rm(appData, {recursive:true, force:true}));
  const profile = path.join(appData, 'Folio');
  const source = await readFile(new URL('../desktop/main.cjs', import.meta.url), 'utf8');
  const require = createRequire(import.meta.url);
  const launch = () => {
    const calls = [];
    let name, userData, quit = false;
    const app = {
      setName(value) {name = value; calls.push('name');},
      getPath(key) {assert.equal(key, 'appData'); return appData;},
      setPath(key, value) {
        assert.equal(key, 'userData');
        assert.equal(value, profile);
        // Electron rejects setPath when the directory does not already exist.
        assert.ok(statSync(value).isDirectory());
        userData = value;
        calls.push('profile');
      },
      setAboutPanelOptions() {},
      requestSingleInstanceLock() {
        assert.equal(name, 'Folio');
        assert.equal(userData, profile);
        assert.deepEqual(calls, ['name', 'profile']);
        calls.push('lock');
        return false; // Exercise startup without launching a server or window.
      },
      quit() {quit = true;},
    };
    runInNewContext(source, {
      require(id) {
        if (id === 'electron') return {app};
        if (id === './system-trust.cjs') return () => {};
        assert.ok(['node:path', 'node:url', 'node:fs'].includes(id));
        return require(id);
      },
      process: {platform:process.platform, title:''},
    }, {filename:'desktop/main.cjs', timeout:1000});
    assert.equal(quit, true);
    assert.deepEqual(calls, ['name', 'profile', 'lock']);
  };
  launch();
  const sentinel = path.join(profile, 'existing-profile-fixture.txt');
  await writeFile(sentinel, 'Synthetic existing profile data');
  launch();
  assert.equal(await readFile(sentinel, 'utf8'), 'Synthetic existing profile data');
});
