import test from 'node:test';
import http from 'node:http';
import {gunzipSync} from 'node:zlib';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createFolioServer } from '../server/index.mjs';

test('disk library, connector boundary, PDF streaming and revision conflicts', async t => {
  const dataDir = await mkdtemp(path.join(tmpdir(), 'folio-test-'));
  let server;
  const launch = async () => { server = await createFolioServer({ dataDir, pubmedLookup:async()=>{throw Error('Fixture DOI has no PubMed match.');} }); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); return `http://127.0.0.1:${server.address().port}`; };
  let base = await launch();
  t.after(async () => { await new Promise(resolve => server.close(resolve)); await rm(dataDir, { recursive: true, force: true }); });
  const call = (route, options = {}) => fetch(base + route, options);
  assert.equal((await call('/api/library')).status, 401);
  assert.equal((await call('/api/session', { headers: { Origin: 'https://evil.example' } })).status, 403);
  assert.equal((await call('/api/session', { headers: { 'Sec-Fetch-Site': 'cross-site' } })).status, 403);
  assert.equal(await new Promise((resolve, reject) => { http.get(base + '/api/session', { headers: { Host: 'evil.example' } }, res => { res.resume(); resolve(res.statusCode); }).on('error', reject); }), 403);
  const session = await call('/api/session'); const { token } = await session.json();
  const cookie = session.headers.get('set-cookie').split(';')[0];
  assert.match(session.headers.get('set-cookie'), /HttpOnly; SameSite=Strict/);
  const auth = { Authorization: `Bearer ${token}` };
  assert.equal((await call('/api/library', { headers: { Cookie: cookie } })).status, 200);
  const ext = 'chrome-extension://' + 'a'.repeat(32);
  assert.equal((await call('/api/library', { headers: { Origin: ext, Cookie: cookie } })).status, 403);
  assert.equal((await call('/api/session', { headers: { Origin: ext, ...auth } })).status, 403);
  assert.equal((await call('/api/library', { headers: { Origin: ext, ...auth } })).status, 200);
  const preflight = await call('/api/capture', { method: 'OPTIONS', headers: { Origin: ext, 'Access-Control-Request-Headers': 'authorization,content-type' } });
  assert.equal(preflight.status, 204); assert.equal(preflight.headers.get('access-control-allow-origin'), ext);
  const capture = body => call('/api/capture', { method: 'POST', headers: { ...auth, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const captured = await (await capture({ title: 'Study', doi: 'https://doi.org/10.1234/ABC', url: 'https://example.com/paper' })).json();
  assert.equal(captured.duplicate, false);
  const duplicate = await (await capture({ title: 'Other', doi: '10.1234/abc' })).json();
  assert.equal(duplicate.duplicate, true); assert.equal(duplicate.paper.id, captured.paper.id); assert.equal(duplicate.paper.title, 'Study');
  assert.equal((await capture({ title: 'Bad', pdfId: '00000000-0000-0000-0000-000000000000' })).status, 400);
  const pdfHeaders = { ...auth, 'Content-Type': 'application/pdf', 'X-Folio-Filename': encodeURIComponent('A study.pdf') };
  assert.equal((await call('/api/pdfs', { method: 'POST', headers: pdfHeaders, body: 'not a pdf' })).status, 400);
  assert.deepEqual(await readdir(path.join(dataDir, 'pdfs')), []);
  const bytes = '%PDF-1.7\nTest file bytes\n%%EOF';
  const uploaded = await (await call('/api/pdfs', { method: 'POST', headers: pdfHeaders, body: bytes })).json();
  const reused=await (await call('/api/pdfs',{method:'POST',headers:pdfHeaders,body:bytes})).json();assert.equal(reused.pdfId,uploaded.pdfId);assert.equal(reused.reused,true);
  assert.equal(uploaded.pdfName, 'A study.pdf'); assert.equal(uploaded.size, bytes.length);
  const ranged = await call(`/api/pdfs/${uploaded.pdfId}`, { headers: { Cookie: cookie, Range: 'bytes=0-4' } });
  assert.equal(ranged.status, 206); assert.equal(await ranged.text(), '%PDF-');
  assert.equal((await call(`/api/pdfs/${uploaded.pdfId}`, { headers: { ...auth, Range: 'bytes=99999-' } })).status, 416);
  const attached = await (await capture({ doi: '10.1234/abc', ...uploaded })).json();
  const downloaded=await call(`/api/pdfs/${uploaded.pdfId}?download=1`,{headers:auth});assert.match(downloaded.headers.get('content-disposition'),/^attachment/);await downloaded.arrayBuffer();
  const backupResponse=await call('/api/backup',{headers:auth});assert.equal(backupResponse.status,200);const backup=gunzipSync(Buffer.from(await backupResponse.arrayBuffer()));assert.equal(backup.subarray(0,12).toString(),'library.json');assert.ok(backup.includes(Buffer.from(bytes)));
  const stats=await (await call('/api/storage',{headers:auth})).json();assert.equal(stats.pdfCount,1);assert.equal(stats.bytes,bytes.length);
  const second=await (await capture({title:'Second reference',doi:'10.5678/other',...uploaded})).json();const sharedStats=await (await call('/api/storage',{headers:auth})).json();assert.equal(sharedStats.savedBytes,bytes.length);
  const sharedLibrary=await (await call('/api/library',{headers:auth})).json();await call('/api/library',{method:'PUT',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify({papers:sharedLibrary.papers.filter(p=>p.id!==second.paper.id),revision:sharedLibrary.revision})});
  assert.equal(attached.paper.pdfId, uploaded.pdfId); assert.equal(attached.paper.title, 'Study');
  assert.equal((await call(`/api/pdfs/${uploaded.pdfId}`, { method: 'DELETE', headers: auth })).status, 409);
  const library = await (await call('/api/library', { headers: auth })).json();
  const put = body => call('/api/library', { method: 'PUT', headers: { ...auth, 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const updates = await Promise.all([put(library), put(library)]);
  assert.deepEqual(updates.map(r => r.status).sort(), [200, 409]);
  assert.equal(JSON.parse(await readFile(path.join(dataDir, 'library.json'))).papers.length, 1);
  await new Promise(resolve => server.close(resolve)); base = await launch();
  const restored = await (await call('/api/library', { headers: auth })).json();
  assert.equal(restored.papers[0].pdfId, uploaded.pdfId);
  assert.equal(await (await call(`/api/pdfs/${uploaded.pdfId}`, { headers: auth })).text(), bytes);
  assert.equal((await put({ papers: [], revision: restored.revision })).status, 200);
  assert.equal((await call(`/api/pdfs/${uploaded.pdfId}`, { method: 'DELETE', headers: auth })).status, 200);
  const large = Buffer.alloc(51 * 1024 * 1024); large.write('%PDF-1.7\n');
  const largeResponse = await call('/api/pdfs', { method: 'POST', headers: pdfHeaders, body: large });
  assert.equal(largeResponse.status, 201);
  assert.equal((await largeResponse.json()).size, large.length);
});
