import {useEffect,useRef,useState,type ReactNode} from 'react';
import {api} from './api';
type Provider='chatgpt'|'openai'|'anthropic';
type Settings={provider:Provider;models:Record<Provider,string>;hasKey:{openai:boolean;anthropic:boolean};secureStorage:boolean;chatgpt:{installed:boolean;connected:boolean;supported?:boolean;reason?:string;error?:string;message?:string}};
type Message={id:string;role:'user'|'assistant';content:string;summary?:boolean;pages?:number[];limited?:boolean;provider:Provider};
type Conversation={enabled:boolean;provider:Provider;messages:Message[];busy?:boolean};
const names={chatgpt:'ChatGPT account',openai:'OpenAI API',anthropic:'Claude API'};
export default function PaperChat({pdfId,page,selection,visualOptions,onPage}:{pdfId:string;page:number;selection:string;visualOptions:{id:string;label:string;page:number}[];onPage:(page:number)=>void}){
 const route=`/api/ai/papers/${pdfId}`;const [settings,setSettings]=useState<Settings|null>(null),[conversation,setConversation]=useState<Conversation|null>(null),[provider,setProvider]=useState<Provider>('chatgpt'),[model,setModel]=useState(''),[key,setKey]=useState(''),[question,setQuestion]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[setup,setSetup]=useState(false),[visuals,setVisuals]=useState(false),[useSelection,setUseSelection]=useState(false),[loginUrl,setLoginUrl]=useState(''),[confirmClear,setConfirmClear]=useState(false);
 const [visualId,setVisualId]=useState(visualOptions[0]?.id||'');
 useEffect(()=>{if(!visualOptions.some(v=>v.id===visualId))setVisualId(visualOptions[0]?.id||'');},[visualOptions,visualId]);
 const chosenVisual=visualOptions.find(v=>v.id===visualId);
 const [captured,setCaptured]=useState({text:selection,page});
 useEffect(()=>{if(selection)setCaptured({text:selection,page});},[selection,page]);
 const active=useRef<AbortController|null>(null),alive=useRef(true),end=useRef<HTMLDivElement>(null);
 function apply(s:Settings){setSettings(s);setProvider(s.provider);setModel(s.models[s.provider]);}
 useEffect(()=>{alive.current=true;const c=new AbortController();void Promise.all([api<Settings>('/api/ai/settings',{signal:c.signal}),api<Conversation>(route,{signal:c.signal})]).then(([s,v])=>{if(!c.signal.aborted){apply(s);setConversation(v);}}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>{alive.current=false;c.abort();active.current?.abort();};},[route]);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'});},[conversation?.messages.length]);
 const connected=settings&&(settings.provider==='chatgpt'?settings.chatgpt.connected&&settings.chatgpt.supported!==false:settings.hasKey[settings.provider]);
 async function request(path:string,method:string,body?:unknown){return api(path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
 async function save(removeKey=false){setBusy(true);setError('');try{const s=await request('/api/ai/settings','POST',{provider,model,key,removeKey}) as Settings;apply(s);setKey('');setConversation(await api<Conversation>(route));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function refresh(){setError('');try{apply(await api<Settings>('/api/ai/settings'));setConversation(await api<Conversation>(route));}catch(e){setError((e as Error).message);}}
 async function login(){setBusy(true);setError('');try{const result=await request('/api/ai/login','POST') as {authUrl:string};const url=new URL(result.authUrl);if(url.protocol!=='https:'||!['auth.openai.com','chatgpt.com'].includes(url.hostname))throw Error('Unexpected sign-in address.');setLoginUrl(url.href);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function ask(summary=false){const c=new AbortController();active.current=c;setBusy(true);setError('');try{const value=await api<Conversation>(route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,summary,page:useSelection&&captured.text?captured.page:page,selection:useSelection?captured.text:'',includeVisuals:visuals&&visualOptions.length>0,visualId}),signal:c.signal});if(alive.current){setConversation(value);setQuestion('');}}catch(e){if(alive.current&&!c.signal.aborted)setError((e as Error).message);}finally{if(alive.current)setBusy(false);}}
 async function enable(){setBusy(true);setError('');try{const value=await request(route,'PUT',{enabled:true,provider:settings!.provider}) as Conversation;setConversation(value);if(!value.messages.some(m=>m.summary))await ask(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function disable(){setBusy(true);try{setConversation(await request(route,'PUT',{enabled:false}) as Conversation);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function clear(){setBusy(true);try{setConversation(await request(route,'DELETE') as Conversation);setConfirmClear(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function answer(message:Message):ReactNode[]{return message.content.split(/(\[p\.\s*\d+\])/g).map((part,i)=>{const match=part.match(/^\[p\.\s*(\d+)\]$/);const n=Number(match?.[1]);return match&&message.pages?.includes(n)?<button className="paper-chat-citation" key={i} onClick={()=>onPage(n)}>{part}</button>:part;});}
 return <section className="paper-chat" aria-label="Ask this paper"><div className="paper-chat-heading"><div><span className="reading-kicker">READING ASSISTANT</span><h3>Ask this paper</h3></div><button onClick={()=>setSetup(!setup)} aria-expanded={setup}>Connection</button></div>
 {error&&<p className="reading-alert" role="alert">{error}</p>}
 {setup&&<div className="paper-chat-settings"><label>Connect using<select value={provider} disabled={busy} onChange={e=>{const p=e.target.value as Provider;setProvider(p);setModel(settings?.models[p]||'');setKey('');}}>{Object.entries(names).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Model ID {provider==='chatgpt'&&'(blank uses account default)'}<input value={model} onChange={e=>setModel(e.target.value)} disabled={busy}/></label>
 {provider!=='chatgpt'&&<><label>API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={settings?.hasKey[provider]?'Key already configured; leave blank to keep':'Paste your API key here'} disabled={busy}/></label><p>API usage is billed by the provider. {settings?.secureStorage?'Keys are encrypted on this computer.':'Keys are kept in memory and must be entered again after Refhaven restarts.'}</p></>}
 <div className="paper-chat-actions"><button disabled={busy} onClick={()=>void save()}>Save connection</button>{provider!=='chatgpt'&&<button disabled={busy} onClick={()=>void save(true)}>Remove key</button>}</div>
 {settings?.provider==='chatgpt'&&<><p>{settings.chatgpt.supported===false?settings.chatgpt.reason:settings.chatgpt.connected?'ChatGPT connected. Uses your account’s available limits.':settings.chatgpt.installed?'ChatGPT is not connected. Sign in using your browser.':'Install Codex CLI or the Codex/ChatGPT desktop app, then restart Refhaven to enable account sign-in. API connections remain available.'}</p>{settings.chatgpt.error&&<p>{settings.chatgpt.error}</p>}<div className="paper-chat-actions"><button disabled={busy||!settings.chatgpt.installed||settings.chatgpt.supported===false} onClick={()=>void login()}>Start ChatGPT sign-in</button><button disabled={busy} onClick={()=>void refresh()}>Check connection</button>{settings.chatgpt.connected&&<button disabled={busy} onClick={()=>{void request('/api/ai/logout','POST').then(()=>refresh()).catch(e=>setError(e.message));}}>Sign out</button>}</div>{loginUrl&&<p><a href={loginUrl} target="_blank" rel="noreferrer">Continue securely in browser ↗</a><br/>After signing in, click Check connection.</p>}</>}
 </div>}
 {!settings||!conversation?<p>Opening paper chat…</p>:<>
 {!conversation.enabled&&<div className="paper-chat-consent"><p>Enable {names[settings.provider]} for this paper to generate a summary and ask questions. Extracted paper text, your questions, and recent chat history will be sent to that provider. Figure/equation images are sent only when selected below. AI answers can be wrong—check the linked pages.</p><p>Chat history stays on this computer. Cloud answers require internet and use your subscription limits or API billing.</p><button className="folio-primary" disabled={busy||!connected} onClick={()=>void enable()}>Enable AI &amp; summarize this paper</button>{!connected&&<button onClick={()=>setSetup(true)}>Set up a connection</button>}</div>}
 <div className="paper-chat-messages" role="log" aria-label="Paper conversation">{conversation.messages.map(m=><div key={m.id} className={`paper-chat-message is-${m.role}`}><strong>{m.role==='user'?'You':m.summary?'Paper summary':names[m.provider]}</strong><div>{answer(m)}</div>{m.limited&&<small>Based on selected excerpts; check the original for omitted content.</small>}</div>)}{busy&&<p role="status">Working…</p>}<div ref={end}/></div>
 {conversation.enabled&&<form onSubmit={e=>{e.preventDefault();void ask();}}><label className="paper-chat-question">Your question<textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={6000} placeholder="What are the main limitations of this study?" disabled={busy}/></label><label className="paper-chat-check"><input type="checkbox" checked={visuals} onChange={e=>setVisuals(e.target.checked)} disabled={busy||!visualOptions.length}/>Include figure/equation images</label>{visuals&&!!visualOptions.length&&<label className="paper-chat-question">Figure or equation<select aria-label="Figure for AI" value={visualId} disabled={busy} onChange={e=>setVisualId(e.target.value)}>{visualOptions.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select>{chosenVisual&&<button type="button" onClick={()=>onPage(chosenVisual.page)}>View source page {chosenVisual.page}</button>}<small>Attaches the selected figure and its legend, or the selected equation. Paper text can come from other pages. Equation numbers follow detected order across the paper and may differ from printed numbers.</small></label>}{!visualOptions.length&&<p>No cached figure or equation images are available. You can still ask about the paper text.</p>}{captured.text&&<label className="paper-chat-check"><input type="checkbox" checked={useSelection} onChange={e=>setUseSelection(e.target.checked)} disabled={busy}/>Ask about selected text (page {captured.page})</label>}<div className="paper-chat-actions"><button type="submit" className="folio-primary" disabled={busy||!question.trim()||!connected}>Ask</button>{!conversation.messages.some(m=>m.summary)&&<button type="button" disabled={busy||!connected} onClick={()=>void ask(true)}>Generate summary</button>}{busy&&<button type="button" onClick={()=>{active.current?.abort();void request(route+'/cancel','POST').catch(e=>setError(e.message));}}>Stop</button>}<button type="button" disabled={busy} onClick={()=>void disable()}>Disable AI</button></div></form>}
 {!!conversation.messages.length&&<div className="paper-chat-actions">{confirmClear?<><span>Delete this saved conversation?</span><button disabled={busy} onClick={()=>void clear()}>Delete</button><button onClick={()=>setConfirmClear(false)}>Keep</button></>:<button disabled={busy} onClick={()=>setConfirmClear(true)}>Clear conversation</button>}</div>}
 </>}
 </section>;
}
